url: "https://kaz-maz.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
title: "anna corfa isehayek" # the name of your site, e.g. ACME Corp.
email: annacorfa@gmail.com